# Generated by Django 4.2.2 on 2023-06-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_curso_turno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='turno',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Mañana'), (2, 'Tarde'), (3, 'Noche')], verbose_name='Turno:'),
        ),
    ]
