# Generated by Django 4.2.2 on 2023-06-14 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_curso_turno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('monotributista', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='curso',
            name='turno',
            field=models.IntegerField(choices=[(1, 'Mañana'), (2, 'Tarde'), (3, 'Noche')], default=1, verbose_name='Turno:'),
        ),
        migrations.AddField(
            model_name='curso',
            name='profesor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.profesor'),
        ),
    ]
